### ISSUE TITLE
PlatformException when I run example code

### ISSUE THREAD

**Issue by yinnxinn** [baka3k/IjkPlayerRecorder#5]
flutter version: 3.7.0

when I run the example code, get error log as follows:
`2023-02-13 19:44:34.936741+0800 Runner[75516:709192] Metal API Validation Enabled
2023-02-13 19:44:35.027603+0800 Runner[75516:709192] GrMtlCommandBuffer: WARNING: Creating MTLCommandBuffer while in background.
2023-02-13 19:44:35.028466+0800 Runner[75516:709192] GrMtlCommandBuffer: WARNING: Creating MTLCommandBuffer while in background.
2023-02-13 19:44:35.287037+0800 Runner[75516:709449] flutter: The Dart VM service is listening on http://127.0.0.1:59608/XkpVyMBdqR8=/
2023-02-13 19:44:37.011708+0800 Runner[75516:709436] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(unregistered_view_type, A UIKitView widget is trying to create a PlatformView with an unregistered type: < VideoViewPlatform >, If you are the author of the PlatformView, make sure `registerViewFactory` is invoked.
See: https://docs.flutter.dev/development/platform-integration/platform-views#on-the-platform-side-1 for more details.
If you are not the author of the PlatformView, make sure to call `GeneratedPluginRegistrant.register`., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:243:5)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:649:44)
<asynchronous suspension>`

could anyone met this problem

**Comment by baka3k** [comment]
@yinnxinn  
It's issue by Flutter wrapper, and related IOS Plugin you used.
Please re-check your IOS plugin again

**Comment by yinnxinn** [comment]
邮件已收到，谢谢
